akretion/ak

ak.py

CC @rvalyi / @sebastienbeau / @hparfr .

add git-diff function

---

ak.py

add upgrade

---

ak/main.py

[REF] ak run now forward all params to the start_openerp cmd

---

ak/main.py

@hparfr can you take a look on it?

[REF] remove run method and hack CommandLocal for logging and dry run

---

ak/main.py

solve https://github.com/akretion/voodoo/issues/57

Update buildout path

---

ak/main.py

Go in your directory and launch "ak module diff my_version_to_diff" and enjoy !
Only module installed in your database will be checked (without having a diff for the po file)

Module diff

---

ak/ak_build.py

IMP link in build cmd

---

ak/ak_build.py

IMP make api name more friendly

---

ak/ak_migrate.py

@hparfr @sebastienbeau @bealdav 
It is not very clean, but I don't think it is worth spend time to make it perfect as this ak migrate feature is only needed to migrate from buildout to spec.yaml and it won't be used in the long term.
Anyway, any suggestions/remarks are welcome
This PR aims to populate the modules variable in spec.yaml file when migrating it from buildout, if we specify a database in option.

Populate modules from database installed modules on ak migrate

---

ak/ak_build.py
tests/links/expected_output.txt
tests/links/spec.yaml
tests/links/test_link.py

Put a relative addons path instead of absolute

IMP set relative path to addons path

---

ak/ak_build.py

[IMP] add default depth, fix generation of link for odoo

---

ak/ak_build.py

Raise an exception if we are not in a viable folder

---

ak/ak_build.py

[FIX] Config was not properly set when it was not spec.yaml

---

ak/ak_build.py
ak/ak_suggest.py
tests/build/test_build_repos-yaml.py

see https://msg.pyyaml.org/load

SECurity yaml.load() https://msg.pyyaml.org/load

---

ak/ak_build.py

Building with a frozen put the odoo src inside external-src.
Frozen file is already in the gitaggregator format and reparsing it
into a repo.yaml move the odoo src code in the external-src
Using directly teh frozen.yaml fix the bug
@hparfr  @florian-dacosta

[FIX] fix build with frozen

---

ak/ak_suggest.py

FIX suggest: if no src tag

---

ak/ak_build.py

First shot to refactore the frozen process.
Concerned issue : https://github.com/akretion/ak/issues/61
@hparfr @sebastienbeau

[IMP] Refactore ak freeze and ak build to manage new frozen process

---

ak/ak_build.py

@hparfr @bealdav @sebastienbeau 
Quick review please?
I'd like to have this merge real fast...
I think just one review is enough for this one!

Fix depth attribute with simplified format

---

ak/ak_build.py

add jobs option for git-aggregate.
By default 2 (instead of 1 in git-aggregate).
Increase perfs.

Add jobs, 2 by default

---

ak/ak_build.py

Reuse function get_repo_key_from_spec

Small refactoring

---

.gitignore
ak/__init__.py
ak/ak_clone.py
ak/ak_sub.py

`$ ak clone` to be done at initalization of the project (when there is no git clone done yet).
It will do a git clone --no-checkout in order to minimize the brandwith used during git fetch.
For the moment only short syntax is supported. :
```yaml
server-tools:
src: https://github.com/oca/server-tools 12.0
modules:
- base_exception
```

[WIP] Add ak clone

---

ak/ak_build.py
ak/ak_clone.py
ak/ak_sub.py

Warn about missing modules in /links
replace print() by logger

Improve links and add warnings

---

requirement.txt

related to https://github.com/acsone/git-aggregator/issues/68 issue
Also see here : https://github.com/Tecnativa/doodba/pull/582

[TMP/FIX] gitaggregator version less than 3

---

ak/ak_build.py
ak/ak_clone.py
ak/ak_sub.py
requirement.txt

Treeless clone

---

ak/ak_sparse.py

and clean a bit the source code

ak_sparse: remove warning about deprecated isdir
